### ISSUE TITLE
Don't rely on master hostnames to create etcd cname index

### ISSUE THREAD

**Issue by dustinblack** [openshift/coredns-mdns#49]
The existing design is explicitly looking for a master hostname split with a "-" character, and picking up the portion after the "-" as the index number to be reused with the etcd cname entries.

https://github.com/openshift/coredns-mdns/blob/bb12f6c7eac7024b1fd6994a23c8cc51e6448149/mdns.go#L61-L64

https://github.com/openshift/coredns-mdns/blob/bb12f6c7eac7024b1fd6994a23c8cc51e6448149/mdns.go#L160

This forces a particular naming convention for the master nodes, which should not be unnecessary. First, this requires a single-hyphenated name with the assumption that what follows the hyphen is a numerical index. Second, because the installer bootstrap system explicitly looks for hostnames `etcd-{0..2}` it means that the index values for the master nodes _must_ be `{0..2}` to match, otherwise the generated cname will not match the etcd client query from the bootstrap system, and the install will timeout waiting for confirmation of the etcd cluster.

I suggest eliminating the `GetIndex` function and re-factoring the loop that generates the etcd cname values to simply increment 0 to N. I don't see why it should be necessary for the etcd cname index to match an index from the master hostname.

**Comment by dustinblack** [comment]
Maybe PR #29 is already addressing this problem?

**Comment by cybertron** [comment]
#29 just moves where this happens. The mapping still exists though.

The reason we can't do a naive enumeration is that if a node goes down or gets replaced it may change the enumeration of the etcd records. For example, consider a cluster of master-a, master-b, and master-c. If we map those to etcd-0, 1, and 2 respectively, then if master-b goes down, the enumeration will map master-c to etcd-1, which will break the cluster because etcd thinks that it should still be called etcd-2. That's why the etcd names are tied to the master names.

Our plan for addressing this is to remove the etcd-specific records altogether and have the etcd SRV record point directly at the master names. The reason it doesn't work that way today is we don't have a way to look up the master names before bootstrapping etcd. We expect the cluster-etcd-operator to fix this though - it will bring up a single-node etcd cluster on the boostrap node, then add the masters to that cluster as they come up. This should address the bootstrap timing issue that we have today (since bootstrap won't be dependent on the master hostnames) and allow us to get rid of the etcd records.

**Comment by cybertron** [comment]
While some of the cname code is still waiting to be removed in #29, we've already stopped publishing the cnames so this should no longer be a problem. Etcd bootstrapping is now handled in a way that doesn't rely on DNS records.
