### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by polarathene** [openshift/coredns-mdns#65]
Putting together an automated build, when this plugin is added with `go get` there is no git tag to pin to a release, so builds won't be immutable.

I can see that releases in this repo are being managed as branches, could they be tagged too? They'd be able to leverage github releases as well if desired.

`go get github.com/openshift/coredns-mdns@db984b5` would be nicer as `go get github.com/openshift/coredns-mdns@v4.5`.

**Comment by cybertron** [comment]
I went ahead and tagged the 4.5 release. Since this isn't part of our normal release management process I can't guarantee how up-to-date the tags will stay though. On the plus side, this repo is a bit of a black sheep in our release process anyway so I have to manually create the branches. I'll try to remember to tag them too.
